* This notebook reviews all the details associated with Linear Algebra for ML

Mark-I - Total Energy generated = 30 * 1 = 30Kj
Mark-II - 4Kj/day multiplied by x = 30


In [4]:
# e = d
# e = 4*(d-30)



## Tensors

* Tensors are ML generalization of vectors and matrices to any number of dimensions 
* 

In [1]:
import torch

In [3]:
t1 = torch.Tensor([[25],[2],[-3],[-23]])

In [4]:
t1.T

tensor([[ 25.,   2.,  -3., -23.]])

In [5]:
import numpy as np

In [6]:
x = np.array([[1,2,3],[56,72,34]])
x

array([[ 1,  2,  3],
       [56, 72, 34]])

In [7]:
y = np.array([[1,4,9],[2,5,8],[3,7,0]])
y

array([[1, 4, 9],
       [2, 5, 8],
       [3, 7, 0]])

In [8]:
np.dot(x,y)

array([[  14,   35,   25],
       [ 302,  822, 1080]])

In [11]:
torch.matmul(torch.from_numpy(x), torch.from_numpy(y))

tensor([[  14,   35,   25],
        [ 302,  822, 1080]])

#### How is matrix inversion helpful in solving a regression problem in supervised learning?

* basic equation of linear regression is y = a + bX assuming X is a matrix of n features and y is a column vector. If b is also represented as a vector of coefficients associated with each X features then bX is a dot product (mat mulplication)
* Assume intercept is 0 thus a = 0
* As inverse of a matrix multiplied by itself is identity matrix, you can calculate using the following equation:
X^-1 . y = b (since X .X^-1 = I and I multipled to any matrix is that matrix)
* Thus solving for b or X coefficients is multiplying the inverse of X with y

In [16]:
u1 = torch.Tensor([2,5,-3]).T
u2 = torch.Tensor([0,-4,6]).T

B = torch.Tensor([[2,0,-1],[-2,3,1],[0,4,-1]])

/var/folders/3b/3q1_jkcx7_jc4vrxbngfsxgc0000gn/T/ipykernel_14743/594887992.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_e2rjusv8ek/croot/pytorch-select_1717607459930/work/aten/src/ATen/native/TensorShape.cpp:3679.)
  u1 = torch.Tensor([2,5,-3]).T


In [17]:
i = torch.Tensor([[1,0,0],[0,1,0],[0,0,1]])

In [18]:
torch.matmul(u1,i)

tensor([ 2.,  5., -3.])

In [19]:
torch.matmul(B, u1)

tensor([ 7.,  8., 23.])

In [53]:
U = torch.stack([u1,u2],dim=1)

In [54]:
torch.matmul(B, U)

tensor([[  7.,  -6.],
        [  8.,  -6.],
        [ 23., -22.]])