* This notebook reviews all the details associated with Linear Algebra for ML

Mark-I - Total Energy generated = 30 * 1 = 30Kj
Mark-II - 4Kj/day multiplied by x = 30


In [4]:
# e = d
# e = 4*(d-30)



## Tensors

* Tensors are ML generalization of vectors and matrices to any number of dimensions 
* 

In [1]:
import torch

In [3]:
t1 = torch.Tensor([[25],[2],[-3],[-23]])

In [4]:
t1.T

tensor([[ 25.,   2.,  -3., -23.]])

In [5]:
import numpy as np

In [6]:
x = np.array([[1,2,3],[56,72,34]])
x

array([[ 1,  2,  3],
       [56, 72, 34]])

In [7]:
y = np.array([[1,4,9],[2,5,8],[3,7,0]])
y

array([[1, 4, 9],
       [2, 5, 8],
       [3, 7, 0]])

In [8]:
np.dot(x,y)

array([[  14,   35,   25],
       [ 302,  822, 1080]])

In [11]:
torch.matmul(torch.from_numpy(x), torch.from_numpy(y))

tensor([[  14,   35,   25],
        [ 302,  822, 1080]])